 drop table if exists post CASCADE;
 create table post
 (
    id bigint generated by default as identity,
    subject varchar(255),
    content varchar(255),
    createdate datetime,
    primary key (id)
 );